#!/bin/bash

#Создание проект

# FUNCTIONS ---------->
usage () {
    echo "$PROGNAME: usage: $PROGNAME [-n name][-t type][-g git]"
}
create_python_project () {
    # check requirements
    [[ -d $name ]] && \
    { echo "Папка с именем проекта уже существует"; return 1;}

    hash git 2>/dev/null || \
    { echo >&2 "Не ненайден git"; return 1; }
    
    hash virtualenv 2>/dev/null || \
    { echo >&2 "Не ненайден virtualenv"; return 1; }

    # create project
    mkdir $name

    if [ -n "$git" ];then
        git clone "${git}" "${name}/."
        touch "${name}/.gitignore"
        echo '/venv/' >> "${name}/.gitignore"
    fi

    virtualenv "${name}/venv"
}

# SCRIPT ---------->

# constant
PROGNAME=$(basename $0)
# variables
name=
git=
type='python'

echo "Создание проекта"

# argument handling
while [[ -n $1 ]]; do
    case $1 in
    -n) name=$2
        shift
        ;;
    -t) type=$2
        shift
        ;;
    -g) git=$2
        shift
        ;;
    -h) usage
        exit
        ;;
    *)  usage
        exit 1
        ;;
    esac
    shift
done

# validation

[[ "$name" =~ ^[[:alpha:]][[:alnum:]_]+$ ]] ||\
{ echo "Не подходящие имя $name";exit 1; }

# control

if [[ "$type" =~ python ]];then
    create_python_project && echo "Проект успешно создан"
else
    echo "Данный тип проекта неизвестен"
fi


